# Generated by Django 5.1.2 on 2025-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion290_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
